spring:
  datasource:
    url: jdbc:mysql://${RDS_HOST:localhost}:${RDS_PORT:3306}/${RDS_DB_FINANCE:finance}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${RDS_USER:postgres}
    password: ${RDS_PASSWORD:postgres}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8050